// SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
// SPDX-License-Identifier: Apache-2.0

#ifndef _SOC_INCLUDE_GUARD_
#define _SOC_INCLUDE_GUARD_

// Include Utility Headers
#include "params.h"

// --- Register blocks not yet API-compatible with the generated headers -------
// Same committed copies as chimera-open (migration tracked in docs/memory-map.md).
#include "regs/soc_regs.h"
#include "regs/cheshire_regs.h"
#include "regs/clint_regs.h"
#include "regs/hyperbus_regs.h"

// --- OpenTitan peripheral registers: generated by reggen ---------------------
// Resolved from CHIMERA_REGGEN_INC_DIR (opentitan_peripherals/sw/include, via
// `make otp`); included without the "regs/" prefix so they resolve from there
// rather than a committed copy (matches the OT DIF driver includes).
#include "gpio_regs.h"
#include "i2c_regs.h"
#include "spi_host_regs.h"

// Include Address Maps (bases derived from the SystemRDL-generated raw header)
#include "addr_maps/soc_addr_map.h"

#endif //_SOC_INCLUDE_GUARD_
